### ISSUE TITLE
Add footer with info and link to repo

### ISSUE THREAD

**Issue by nucliweb** [rviscomi/capo.js#26]
We can add a footer to add info/documentation and link to this repo

## Code

```html
<footer class="capo-footer">
  <ul>
    <li>Click in the rectangles to see the element in the console</li>
    <li><a href="https://github.com/rviscomi/capo.js" target="_blank">GitHub</a></li>
  </ul>
</footer>
```

```css
:root {
  --text-colot: #353535;
}

body {
  color: var(--text-colot);
  padding: 0;
  margin: 0;
}

.capo-footer {
  padding: 1ch;

  & ul {
    display: flex;
    justify-content: space-between;
    list-style: none;
    margin: 0;
    padding: 0;
    width: 100%;
  }

  & a {
    color: var(--text-colot);
  }
}


```

## Screenshot

![footer](https://github.com/rviscomi/capo.js/assets/1307927/9320cc46-0bde-4705-93b4-4a96ff6b18fc)
